//! Integration tests for the prost-generated canal protocol types.
//! The generated file is regenerated by build.rs, so tests live here.
use canal_proto::*;
use prost::Message;

fn roundtrip<T: Message + Default + PartialEq + std::fmt::Debug>(msg: &T) -> T {
    let bytes = msg.encode_to_vec();
    let decoded = T::decode(bytes.as_slice()).expect("decode should succeed");
    assert_eq!(&decoded, msg, "roundtrip mismatch");
    decoded
}

// ---------- Packet ----------

#[test]
fn test_packet_roundtrip_all_fields() {
    let packet = Packet {
        r#type: PacketType::Get as i32,
        body: vec![1, 2, 3, 4],
        magic_number_present: Some(packet::MagicNumberPresent::MagicNumber(17)),
        version_present: Some(packet::VersionPresent::Version(1)),
        compression_present: Some(packet::CompressionPresent::Compression(
            Compression::Zlib as i32,
        )),
    };
    roundtrip(&packet);
}

#[test]
fn test_packet_default() {
    let packet = Packet::default();
    assert_eq!(packet.r#type, 0);
    assert_eq!(
        PacketType::try_from(packet.r#type).unwrap(),
        PacketType::Packagetypecompatibleproto2
    );
    assert!(packet.body.is_empty());
    assert!(packet.magic_number_present.is_none());
    assert!(packet.version_present.is_none());
    assert!(packet.compression_present.is_none());
}

#[test]
fn test_packet_decode_truncated_errors() {
    // Truncated varint for tag 3 field type
    assert!(Packet::decode(&[0x18u8][..]).is_err());
    // Completely empty buffer decodes to default
    let p = Packet::decode(&[][..]).unwrap();
    assert_eq!(p, Packet::default());
}

// ---------- Handshake / ClientAuth / Ack ----------

#[test]
fn test_handshake_roundtrip() {
    let hs = Handshake {
        seeds: vec![0xde, 0xad, 0xbe, 0xef],
        supported_compressions: Compression::Gzip as i32,
        communication_encoding_present: Some(
            handshake::CommunicationEncodingPresent::CommunicationEncoding("utf8".into()),
        ),
    };
    roundtrip(&hs);
    // Default: no encoding present
    assert!(Handshake::default()
        .communication_encoding_present
        .is_none());
}

#[test]
fn test_client_auth_roundtrip() {
    let auth = ClientAuth {
        username: "canal".into(),
        password: vec![1, 2, 3],
        destination: "example".into(),
        client_id: "1001".into(),
        filter: ".*\\..*".into(),
        start_timestamp: 1700000000,
        net_read_timeout_present: Some(client_auth::NetReadTimeoutPresent::NetReadTimeout(30)),
        net_write_timeout_present: Some(client_auth::NetWriteTimeoutPresent::NetWriteTimeout(30)),
    };
    roundtrip(&auth);
    assert!(ClientAuth::default().net_read_timeout_present.is_none());
}

#[test]
fn test_ack_roundtrip() {
    let ack_ok = Ack {
        error_message: String::new(),
        error_code_present: None,
    };
    roundtrip(&ack_ok);
    let ack_err = Ack {
        error_message: "compression not supported".into(),
        error_code_present: Some(ack::ErrorCodePresent::ErrorCode(1)),
    };
    roundtrip(&ack_err);
}

#[test]
fn test_client_ack_roundtrip() {
    let ca = ClientAck {
        destination: "example".into(),
        client_id: "1001".into(),
        batch_id: 42,
    };
    roundtrip(&ca);
}

// ---------- Sub / Unsub / Get / Messages / Dump / ClientRollback ----------

#[test]
fn test_sub_unsub_roundtrip() {
    let sub = Sub {
        destination: "example".into(),
        client_id: "1001".into(),
        filter: "test_db\\.users".into(),
    };
    roundtrip(&sub);
    let unsub = Unsub {
        destination: "example".into(),
        client_id: "1001".into(),
        filter: "test_db\\.users".into(),
    };
    roundtrip(&unsub);
}

#[test]
fn test_get_roundtrip_all_oneofs() {
    let get = Get {
        destination: "example".into(),
        client_id: "1001".into(),
        fetch_size: 100,
        timeout_present: Some(get::TimeoutPresent::Timeout(-1)),
        unit_present: Some(get::UnitPresent::Unit(2)),
        auto_ack_present: Some(get::AutoAckPresent::AutoAck(true)),
    };
    roundtrip(&get);
    // Defaults: no oneof fields present
    let d = Get::default();
    assert!(d.timeout_present.is_none());
    assert!(d.unit_present.is_none());
    assert!(d.auto_ack_present.is_none());
}

#[test]
fn test_messages_roundtrip() {
    let msgs = Messages {
        batch_id: 7,
        messages: vec![vec![1, 2], vec![], vec![0xff, 0x00]],
    };
    roundtrip(&msgs);
    assert_eq!(msgs.messages.len(), 3);
}

#[test]
fn test_dump_roundtrip() {
    let dump_with_ts = Dump {
        journal: "mysql-bin.000001".into(),
        position: 120,
        timestamp_present: Some(dump::TimestampPresent::Timestamp(1700000000)),
    };
    roundtrip(&dump_with_ts);
    assert!(Dump::default().timestamp_present.is_none());
}

#[test]
fn test_client_rollback_roundtrip() {
    let rb = ClientRollback {
        destination: "example".into(),
        client_id: "1001".into(),
        batch_id: 5,
    };
    roundtrip(&rb);
}

// ---------- Entry / Header / Column / RowChange ----------

#[test]
fn test_entry_roundtrip_with_header() {
    let entry = Entry {
        header: Some(Header {
            logfile_name: "mysql-bin.000001".into(),
            logfile_offset: 120,
            server_id: 1,
            serveren_code: "utf8".into(),
            execute_time: 1700000000,
            schema_name: "test_db".into(),
            table_name: "users".into(),
            event_length: 1024,
            props: vec![Pair {
                key: "k".into(),
                value: "v".into(),
            }],
            gtid: "uuid:1-10".into(),
            version_present: Some(header::VersionPresent::Version(1)),
            source_type_present: Some(header::SourceTypePresent::SourceType(Type::Mysql as i32)),
            event_type_present: Some(header::EventTypePresent::EventType(
                EventType::Insert as i32,
            )),
        }),
        store_value: vec![0xab, 0xcd],
        entry_type_present: Some(entry::EntryTypePresent::EntryType(
            EntryType::Rowdata as i32,
        )),
    };
    let decoded = roundtrip(&entry);
    assert_eq!(
        decoded.header.unwrap().schema_name,
        "test_db",
        "schema name must survive roundtrip"
    );
}

#[test]
fn test_entry_default() {
    let e = Entry::default();
    assert!(e.header.is_none());
    assert!(e.store_value.is_empty());
    assert!(e.entry_type_present.is_none());
}

#[test]
fn test_column_roundtrip() {
    let col = Column {
        index: 0,
        sql_type: 4,
        name: "id".into(),
        is_key: true,
        updated: true,
        props: vec![],
        value: "42".into(),
        length: 2,
        mysql_type: "BIGINT".into(),
        is_null_present: Some(column::IsNullPresent::IsNull(false)),
    };
    roundtrip(&col);
    assert!(Column::default().is_null_present.is_none());
}

#[test]
fn test_row_data_roundtrip() {
    let rd = RowData {
        before_columns: vec![Column {
            index: 0,
            sql_type: 253,
            name: "name".into(),
            is_key: false,
            updated: false,
            props: vec![],
            value: "old".into(),
            length: 3,
            mysql_type: "VARCHAR".into(),
            is_null_present: None,
        }],
        after_columns: vec![],
        props: vec![],
    };
    roundtrip(&rd);
}

#[test]
fn test_row_change_roundtrip() {
    let rc = RowChange {
        table_id: 42,
        sql: "ALTER TABLE t ADD COLUMN c INT".into(),
        row_datas: vec![RowData {
            before_columns: vec![],
            after_columns: vec![],
            props: vec![],
        }],
        props: vec![],
        ddl_schema_name: "test_db".into(),
        event_type_present: Some(row_change::EventTypePresent::EventType(
            EventType::Update as i32,
        )),
        is_ddl_present: Some(row_change::IsDdlPresent::IsDdl(true)),
    };
    roundtrip(&rc);
    // Default: UPDATE implied, is_ddl false
    let d = RowChange::default();
    assert!(d.event_type_present.is_none());
    assert!(d.is_ddl_present.is_none());
    assert!(d.sql.is_empty());
}

#[test]
fn test_transaction_begin_end_roundtrip() {
    let tb = TransactionBegin {
        execute_time: 1700000000,
        transaction_id: "txn-1".into(),
        props: vec![],
        thread_id: 99,
    };
    roundtrip(&tb);
    let te = TransactionEnd {
        execute_time: 1700000000,
        transaction_id: "txn-1".into(),
        props: vec![],
    };
    roundtrip(&te);
}

// ---------- Enums ----------

#[test]
fn test_compression_enum_helpers() {
    for v in [
        Compression::Compressioncompatibleproto2,
        Compression::None,
        Compression::Zlib,
        Compression::Gzip,
        Compression::Lzf,
    ] {
        assert_eq!(Compression::from_str_name(v.as_str_name()), Some(v));
        assert_eq!(v as i32, Compression::try_from(v as i32).unwrap() as i32);
    }
    assert_eq!(Compression::from_str_name("BOGUS"), None);
    // Wire values are stable
    assert_eq!(Compression::None as i32, 1);
    assert_eq!(Compression::Zlib as i32, 2);
    assert_eq!(Compression::Gzip as i32, 3);
}

#[test]
fn test_packet_type_enum_helpers() {
    for v in [
        PacketType::Packagetypecompatibleproto2,
        PacketType::Handshake,
        PacketType::Clientauthentication,
        PacketType::Ack,
        PacketType::Subscription,
        PacketType::Unsubscription,
        PacketType::Get,
        PacketType::Messages,
        PacketType::Clientack,
        PacketType::Shutdown,
        PacketType::Dump,
        PacketType::Heartbeat,
        PacketType::Clientrollback,
    ] {
        assert_eq!(PacketType::from_str_name(v.as_str_name()), Some(v));
    }
    assert_eq!(PacketType::from_str_name("BOGUS"), None);
    // Wire values are stable
    assert_eq!(PacketType::Handshake as i32, 1);
    assert_eq!(PacketType::Heartbeat as i32, 11);
}

#[test]
fn test_entry_type_enum_helpers_and_wire_values() {
    for v in [
        EntryType::Entrytypecompatibleproto2,
        EntryType::Transactionbegin,
        EntryType::Rowdata,
        EntryType::Transactionend,
        EntryType::Innerheartbeat,
        EntryType::Gtidlog,
    ] {
        assert_eq!(EntryType::from_str_name(v.as_str_name()), Some(v));
    }
    assert_eq!(EntryType::from_str_name("BOGUS"), None);
    // Wire compatibility preserved after HEARTBEAT -> INNERHEARTBEAT rename
    assert_eq!(EntryType::Innerheartbeat as i32, 4);
    assert_eq!(EntryType::Rowdata as i32, 2);
}

#[test]
fn test_event_type_enum_helpers_and_wire_values() {
    for v in [
        EventType::Eventtypecompatibleproto2,
        EventType::Insert,
        EventType::Update,
        EventType::Delete,
        EventType::Create,
        EventType::Alter,
        EventType::Erase,
        EventType::Query,
        EventType::Truncate,
        EventType::Rename,
        EventType::Cindex,
        EventType::Dindex,
        EventType::Gtid,
        EventType::Xacommit,
        EventType::Xarollback,
        EventType::Mheartbeat,
    ] {
        assert_eq!(EventType::from_str_name(v.as_str_name()), Some(v));
    }
    assert_eq!(EventType::from_str_name("BOGUS"), None);
    // Wire values expected by canal_common::EventType::from_proto
    assert_eq!(EventType::Query as i32, 7);
    assert_eq!(EventType::Xacommit as i32, 13);
    assert_eq!(EventType::Mheartbeat as i32, 15);
}

#[test]
fn test_type_enum_helpers() {
    for v in [
        Type::Typecompatibleproto2,
        Type::Oracle,
        Type::Mysql,
        Type::Pgsql,
    ] {
        assert_eq!(Type::from_str_name(v.as_str_name()), Some(v));
    }
    assert_eq!(Type::from_str_name("BOGUS"), None);
    assert_eq!(Type::Mysql as i32, 2);
}

// ---------- Pair ----------

#[test]
fn test_pair_roundtrip() {
    let pair = Pair {
        key: "gtid".into(),
        value: "uuid:1-10".into(),
    };
    roundtrip(&pair);
    assert_eq!(Pair::default().key, "");
}
