[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
name = "canal-rust"
version = "1.0.3"
edition = "2021"
license = "Apache-2.0"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
prost = "0.13"
prost-types = "0.13"
bytes = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
regex = "1"
serde_json = "1"
futures = "0.3"
rdkafka = { version = "0.36", features = ["tokio"] }
axum = "0.7"
metrics = "0.23"
metrics-exporter-prometheus = "0.15"
