[package]
name = "canal-admin"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
axum.workspace = true
serde.workspace = true
tracing.workspace = true
async-trait.workspace = true
canal-common = { path = "../canal-common" }
canal-instance = { path = "../canal-instance" }
