// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Packet {
    #[prost(enumeration = "PacketType", tag = "3")]
    pub r#type: i32,
    #[prost(bytes = "vec", tag = "5")]
    pub body: ::prost::alloc::vec::Vec<u8>,
    /// \[default = 17\];
    #[prost(oneof = "packet::MagicNumberPresent", tags = "1")]
    pub magic_number_present: ::core::option::Option<packet::MagicNumberPresent>,
    /// \[default = 1\];
    #[prost(oneof = "packet::VersionPresent", tags = "2")]
    pub version_present: ::core::option::Option<packet::VersionPresent>,
    /// \[default = NONE\];
    #[prost(oneof = "packet::CompressionPresent", tags = "4")]
    pub compression_present: ::core::option::Option<packet::CompressionPresent>,
}
/// Nested message and enum types in `Packet`.
pub mod packet {
    /// \[default = 17\];
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum MagicNumberPresent {
        #[prost(int32, tag = "1")]
        MagicNumber(i32),
    }
    /// \[default = 1\];
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum VersionPresent {
        #[prost(int32, tag = "2")]
        Version(i32),
    }
    /// \[default = NONE\];
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum CompressionPresent {
        #[prost(enumeration = "super::Compression", tag = "4")]
        Compression(i32),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HeartBeat {
    #[prost(int64, tag = "1")]
    pub send_timestamp: i64,
    #[prost(int64, tag = "2")]
    pub start_timestamp: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Handshake {
    #[prost(bytes = "vec", tag = "2")]
    pub seeds: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "Compression", tag = "3")]
    pub supported_compressions: i32,
    ///   \[default = "utf8"\];
    #[prost(oneof = "handshake::CommunicationEncodingPresent", tags = "1")]
    pub communication_encoding_present: ::core::option::Option<
        handshake::CommunicationEncodingPresent,
    >,
}
/// Nested message and enum types in `Handshake`.
pub mod handshake {
    ///   \[default = "utf8"\];
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum CommunicationEncodingPresent {
        #[prost(string, tag = "1")]
        CommunicationEncoding(::prost::alloc::string::String),
    }
}
/// client authentication
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientAuth {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    /// hashed password with seeds from Handshake message
    #[prost(bytes = "vec", tag = "2")]
    pub password: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "5")]
    pub destination: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub filter: ::prost::alloc::string::String,
    #[prost(int64, tag = "8")]
    pub start_timestamp: i64,
    /// \[default = 0\]
    #[prost(oneof = "client_auth::NetReadTimeoutPresent", tags = "3")]
    pub net_read_timeout_present: ::core::option::Option<
        client_auth::NetReadTimeoutPresent,
    >,
    /// \[default = 0\];
    #[prost(oneof = "client_auth::NetWriteTimeoutPresent", tags = "4")]
    pub net_write_timeout_present: ::core::option::Option<
        client_auth::NetWriteTimeoutPresent,
    >,
}
/// Nested message and enum types in `ClientAuth`.
pub mod client_auth {
    /// \[default = 0\]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum NetReadTimeoutPresent {
        /// in seconds
        #[prost(int32, tag = "3")]
        NetReadTimeout(i32),
    }
    /// \[default = 0\];
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum NetWriteTimeoutPresent {
        /// in seconds
        #[prost(int32, tag = "4")]
        NetWriteTimeout(i32),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Ack {
    /// if something like compression is not supported, erorr_message will tell about it.
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
    /// \[default = 0\]
    #[prost(oneof = "ack::ErrorCodePresent", tags = "1")]
    pub error_code_present: ::core::option::Option<ack::ErrorCodePresent>,
}
/// Nested message and enum types in `Ack`.
pub mod ack {
    /// \[default = 0\]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum ErrorCodePresent {
        #[prost(int32, tag = "1")]
        ErrorCode(i32),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientAck {
    #[prost(string, tag = "1")]
    pub destination: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub batch_id: i64,
}
/// subscription
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Sub {
    #[prost(string, tag = "1")]
    pub destination: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub filter: ::prost::alloc::string::String,
}
/// Unsubscription
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Unsub {
    #[prost(string, tag = "1")]
    pub destination: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub filter: ::prost::alloc::string::String,
}
///   PullRequest
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Get {
    #[prost(string, tag = "1")]
    pub destination: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub fetch_size: i32,
    /// \[default = -1\]
    #[prost(oneof = "get::TimeoutPresent", tags = "4")]
    pub timeout_present: ::core::option::Option<get::TimeoutPresent>,
    /// \[default = 2\]
    #[prost(oneof = "get::UnitPresent", tags = "5")]
    pub unit_present: ::core::option::Option<get::UnitPresent>,
    /// \[default = false\]
    #[prost(oneof = "get::AutoAckPresent", tags = "6")]
    pub auto_ack_present: ::core::option::Option<get::AutoAckPresent>,
}
/// Nested message and enum types in `Get`.
pub mod get {
    /// \[default = -1\]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum TimeoutPresent {
        /// 默认-1时代表不控制
        #[prost(int64, tag = "4")]
        Timeout(i64),
    }
    /// \[default = 2\]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum UnitPresent {
        /// 数字类型，0:纳秒,1:微秒,2:毫秒,3:秒,4:分钟,5:小时,6:天
        #[prost(int32, tag = "5")]
        Unit(i32),
    }
    /// \[default = false\]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum AutoAckPresent {
        /// 是否自动ack
        #[prost(bool, tag = "6")]
        AutoAck(bool),
    }
}
///
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Messages {
    #[prost(int64, tag = "1")]
    pub batch_id: i64,
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub messages: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
/// TBD when new packets are required
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dump {
    #[prost(string, tag = "1")]
    pub journal: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub position: i64,
    /// \[default = 0\]
    #[prost(oneof = "dump::TimestampPresent", tags = "3")]
    pub timestamp_present: ::core::option::Option<dump::TimestampPresent>,
}
/// Nested message and enum types in `Dump`.
pub mod dump {
    /// \[default = 0\]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum TimestampPresent {
        #[prost(int64, tag = "3")]
        Timestamp(i64),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClientRollback {
    #[prost(string, tag = "1")]
    pub destination: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub batch_id: i64,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Compression {
    Compressioncompatibleproto2 = 0,
    None = 1,
    Zlib = 2,
    Gzip = 3,
    Lzf = 4,
}
impl Compression {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Compressioncompatibleproto2 => "COMPRESSIONCOMPATIBLEPROTO2",
            Self::None => "NONE",
            Self::Zlib => "ZLIB",
            Self::Gzip => "GZIP",
            Self::Lzf => "LZF",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMPRESSIONCOMPATIBLEPROTO2" => Some(Self::Compressioncompatibleproto2),
            "NONE" => Some(Self::None),
            "ZLIB" => Some(Self::Zlib),
            "GZIP" => Some(Self::Gzip),
            "LZF" => Some(Self::Lzf),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PacketType {
    /// compatible
    Packagetypecompatibleproto2 = 0,
    Handshake = 1,
    Clientauthentication = 2,
    Ack = 3,
    Subscription = 4,
    Unsubscription = 5,
    Get = 6,
    Messages = 7,
    Clientack = 8,
    /// management part
    Shutdown = 9,
    /// integration
    Dump = 10,
    Heartbeat = 11,
    Clientrollback = 12,
}
impl PacketType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Packagetypecompatibleproto2 => "PACKAGETYPECOMPATIBLEPROTO2",
            Self::Handshake => "HANDSHAKE",
            Self::Clientauthentication => "CLIENTAUTHENTICATION",
            Self::Ack => "ACK",
            Self::Subscription => "SUBSCRIPTION",
            Self::Unsubscription => "UNSUBSCRIPTION",
            Self::Get => "GET",
            Self::Messages => "MESSAGES",
            Self::Clientack => "CLIENTACK",
            Self::Shutdown => "SHUTDOWN",
            Self::Dump => "DUMP",
            Self::Heartbeat => "HEARTBEAT",
            Self::Clientrollback => "CLIENTROLLBACK",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PACKAGETYPECOMPATIBLEPROTO2" => Some(Self::Packagetypecompatibleproto2),
            "HANDSHAKE" => Some(Self::Handshake),
            "CLIENTAUTHENTICATION" => Some(Self::Clientauthentication),
            "ACK" => Some(Self::Ack),
            "SUBSCRIPTION" => Some(Self::Subscription),
            "UNSUBSCRIPTION" => Some(Self::Unsubscription),
            "GET" => Some(Self::Get),
            "MESSAGES" => Some(Self::Messages),
            "CLIENTACK" => Some(Self::Clientack),
            "SHUTDOWN" => Some(Self::Shutdown),
            "DUMP" => Some(Self::Dump),
            "HEARTBEAT" => Some(Self::Heartbeat),
            "CLIENTROLLBACK" => Some(Self::Clientrollback),
            _ => None,
        }
    }
}
/// ***************************************************************
/// message model
/// 如果要在Enum中新增类型，确保以前的类型的下标值不变.
/// **************************************************************
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Entry {
    /// *协议头部信息*
    #[prost(message, optional, tag = "1")]
    pub header: ::core::option::Option<Header>,
    /// *传输的二进制数组*
    #[prost(bytes = "vec", tag = "3")]
    pub store_value: ::prost::alloc::vec::Vec<u8>,
    /// /**打散后的事件类型**/ \[default = ROWDATA\]
    #[prost(oneof = "entry::EntryTypePresent", tags = "2")]
    pub entry_type_present: ::core::option::Option<entry::EntryTypePresent>,
}
/// Nested message and enum types in `Entry`.
pub mod entry {
    /// /**打散后的事件类型**/ \[default = ROWDATA\]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum EntryTypePresent {
        #[prost(enumeration = "super::EntryType", tag = "2")]
        EntryType(i32),
    }
}
/// *message Header*
///
/// *协议的版本号*
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Header {
    /// *binlog/redolog 文件名*
    #[prost(string, tag = "2")]
    pub logfile_name: ::prost::alloc::string::String,
    /// *binlog/redolog 文件的偏移位置*
    #[prost(int64, tag = "3")]
    pub logfile_offset: i64,
    /// *服务端serverId*
    #[prost(int64, tag = "4")]
    pub server_id: i64,
    /// * 变更数据的编码 *
    #[prost(string, tag = "5")]
    pub serveren_code: ::prost::alloc::string::String,
    /// *变更数据的执行时间 *
    #[prost(int64, tag = "6")]
    pub execute_time: i64,
    /// * 变更数据的schemaname*
    #[prost(string, tag = "8")]
    pub schema_name: ::prost::alloc::string::String,
    /// *变更数据的tablename*
    #[prost(string, tag = "9")]
    pub table_name: ::prost::alloc::string::String,
    /// *每个event的长度*
    #[prost(int64, tag = "10")]
    pub event_length: i64,
    /// *预留扩展*
    #[prost(message, repeated, tag = "12")]
    pub props: ::prost::alloc::vec::Vec<Pair>,
    /// *当前事务的gitd*
    #[prost(string, tag = "13")]
    pub gtid: ::prost::alloc::string::String,
    /// \[default = 1\]
    #[prost(oneof = "header::VersionPresent", tags = "1")]
    pub version_present: ::core::option::Option<header::VersionPresent>,
    /// \[default = MYSQL\]
    #[prost(oneof = "header::SourceTypePresent", tags = "7")]
    pub source_type_present: ::core::option::Option<header::SourceTypePresent>,
    /// \[default = UPDATE\]
    #[prost(oneof = "header::EventTypePresent", tags = "11")]
    pub event_type_present: ::core::option::Option<header::EventTypePresent>,
}
/// Nested message and enum types in `Header`.
pub mod header {
    /// \[default = 1\]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum VersionPresent {
        #[prost(int32, tag = "1")]
        Version(i32),
    }
    /// \[default = MYSQL\]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum SourceTypePresent {
        #[prost(enumeration = "super::Type", tag = "7")]
        SourceType(i32),
    }
    /// \[default = UPDATE\]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum EventTypePresent {
        #[prost(enumeration = "super::EventType", tag = "11")]
        EventType(i32),
    }
}
/// *每个字段的数据结构*
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Column {
    /// *字段下标*
    #[prost(int32, tag = "1")]
    pub index: i32,
    /// *字段java中类型*
    #[prost(int32, tag = "2")]
    pub sql_type: i32,
    /// *字段名称(忽略大小写)，在mysql中是没有的*
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    /// *是否是主键*
    #[prost(bool, tag = "4")]
    pub is_key: bool,
    /// *如果EventType=UPDATE,用于标识这个字段值是否有修改*
    #[prost(bool, tag = "5")]
    pub updated: bool,
    /// *预留扩展*
    #[prost(message, repeated, tag = "7")]
    pub props: ::prost::alloc::vec::Vec<Pair>,
    /// * 字段值,timestamp,Datetime是一个时间格式的文本 *
    #[prost(string, tag = "8")]
    pub value: ::prost::alloc::string::String,
    /// * 对应数据对象原始长度 *
    #[prost(int32, tag = "9")]
    pub length: i32,
    /// *字段mysql类型*
    #[prost(string, tag = "10")]
    pub mysql_type: ::prost::alloc::string::String,
    /// \[default = false\]
    #[prost(oneof = "column::IsNullPresent", tags = "6")]
    pub is_null_present: ::core::option::Option<column::IsNullPresent>,
}
/// Nested message and enum types in `Column`.
pub mod column {
    /// \[default = false\]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum IsNullPresent {
        #[prost(bool, tag = "6")]
        IsNull(bool),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RowData {
    /// * 字段信息，增量数据(修改前,删除前) *
    #[prost(message, repeated, tag = "1")]
    pub before_columns: ::prost::alloc::vec::Vec<Column>,
    /// * 字段信息，增量数据(修改后,新增后)  *
    #[prost(message, repeated, tag = "2")]
    pub after_columns: ::prost::alloc::vec::Vec<Column>,
    /// *预留扩展*
    #[prost(message, repeated, tag = "3")]
    pub props: ::prost::alloc::vec::Vec<Pair>,
}
/// *message row 每行变更数据的数据结构*
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RowChange {
    /// *tableId,由数据库产生*
    #[prost(int64, tag = "1")]
    pub table_id: i64,
    /// * ddl/query的sql语句  *
    #[prost(string, tag = "11")]
    pub sql: ::prost::alloc::string::String,
    /// * 一次数据库变更可能存在多行  *
    #[prost(message, repeated, tag = "12")]
    pub row_datas: ::prost::alloc::vec::Vec<RowData>,
    /// *预留扩展*
    #[prost(message, repeated, tag = "13")]
    pub props: ::prost::alloc::vec::Vec<Pair>,
    /// * ddl/query的schemaName，会存在跨库ddl，需要保留执行ddl的当前schemaName  *
    #[prost(string, tag = "14")]
    pub ddl_schema_name: ::prost::alloc::string::String,
    /// \[default = UPDATE\]
    #[prost(oneof = "row_change::EventTypePresent", tags = "2")]
    pub event_type_present: ::core::option::Option<row_change::EventTypePresent>,
    /// \[default = false\]
    #[prost(oneof = "row_change::IsDdlPresent", tags = "10")]
    pub is_ddl_present: ::core::option::Option<row_change::IsDdlPresent>,
}
/// Nested message and enum types in `RowChange`.
pub mod row_change {
    /// \[default = UPDATE\]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum EventTypePresent {
        #[prost(enumeration = "super::EventType", tag = "2")]
        EventType(i32),
    }
    /// \[default = false\]
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum IsDdlPresent {
        #[prost(bool, tag = "10")]
        IsDdl(bool),
    }
}
/// *开始事务的一些信息*
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionBegin {
    /// *已废弃，请使用header里的executeTime*
    #[prost(int64, tag = "1")]
    pub execute_time: i64,
    /// *已废弃，Begin里不提供事务id*
    #[prost(string, tag = "2")]
    pub transaction_id: ::prost::alloc::string::String,
    /// *预留扩展*
    #[prost(message, repeated, tag = "3")]
    pub props: ::prost::alloc::vec::Vec<Pair>,
    /// *执行的thread Id*
    #[prost(int64, tag = "4")]
    pub thread_id: i64,
}
/// *结束事务的一些信息*
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionEnd {
    /// *已废弃，请使用header里的executeTime*
    #[prost(int64, tag = "1")]
    pub execute_time: i64,
    /// *事务号*
    #[prost(string, tag = "2")]
    pub transaction_id: ::prost::alloc::string::String,
    /// *预留扩展*
    #[prost(message, repeated, tag = "3")]
    pub props: ::prost::alloc::vec::Vec<Pair>,
}
/// *预留扩展*
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Pair {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
/// *打散后的事件类型，主要用于标识事务的开始，变更数据，结束*
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EntryType {
    Entrytypecompatibleproto2 = 0,
    Transactionbegin = 1,
    Rowdata = 2,
    /// * 心跳类型，内部使用，外部暂不可见，可忽略 *
    Transactionend = 3,
    /// * Renamed from HEARTBEAT to INNERHEARTBEAT to avoid C++ scoping conflict
    /// with PacketType.HEARTBEAT in CanalProtocol.proto. *
    Innerheartbeat = 4,
    Gtidlog = 5,
}
impl EntryType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Entrytypecompatibleproto2 => "ENTRYTYPECOMPATIBLEPROTO2",
            Self::Transactionbegin => "TRANSACTIONBEGIN",
            Self::Rowdata => "ROWDATA",
            Self::Transactionend => "TRANSACTIONEND",
            Self::Innerheartbeat => "INNERHEARTBEAT",
            Self::Gtidlog => "GTIDLOG",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ENTRYTYPECOMPATIBLEPROTO2" => Some(Self::Entrytypecompatibleproto2),
            "TRANSACTIONBEGIN" => Some(Self::Transactionbegin),
            "ROWDATA" => Some(Self::Rowdata),
            "TRANSACTIONEND" => Some(Self::Transactionend),
            "INNERHEARTBEAT" => Some(Self::Innerheartbeat),
            "GTIDLOG" => Some(Self::Gtidlog),
            _ => None,
        }
    }
}
/// * 事件类型 *
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EventType {
    Eventtypecompatibleproto2 = 0,
    Insert = 1,
    Update = 2,
    Delete = 3,
    Create = 4,
    Alter = 5,
    Erase = 6,
    Query = 7,
    Truncate = 8,
    Rename = 9,
    /// *CREATE INDEX*
    Cindex = 10,
    Dindex = 11,
    Gtid = 12,
    /// * XA *
    Xacommit = 13,
    Xarollback = 14,
    /// * MASTER HEARTBEAT *
    Mheartbeat = 15,
}
impl EventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Eventtypecompatibleproto2 => "EVENTTYPECOMPATIBLEPROTO2",
            Self::Insert => "INSERT",
            Self::Update => "UPDATE",
            Self::Delete => "DELETE",
            Self::Create => "CREATE",
            Self::Alter => "ALTER",
            Self::Erase => "ERASE",
            Self::Query => "QUERY",
            Self::Truncate => "TRUNCATE",
            Self::Rename => "RENAME",
            Self::Cindex => "CINDEX",
            Self::Dindex => "DINDEX",
            Self::Gtid => "GTID",
            Self::Xacommit => "XACOMMIT",
            Self::Xarollback => "XAROLLBACK",
            Self::Mheartbeat => "MHEARTBEAT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EVENTTYPECOMPATIBLEPROTO2" => Some(Self::Eventtypecompatibleproto2),
            "INSERT" => Some(Self::Insert),
            "UPDATE" => Some(Self::Update),
            "DELETE" => Some(Self::Delete),
            "CREATE" => Some(Self::Create),
            "ALTER" => Some(Self::Alter),
            "ERASE" => Some(Self::Erase),
            "QUERY" => Some(Self::Query),
            "TRUNCATE" => Some(Self::Truncate),
            "RENAME" => Some(Self::Rename),
            "CINDEX" => Some(Self::Cindex),
            "DINDEX" => Some(Self::Dindex),
            "GTID" => Some(Self::Gtid),
            "XACOMMIT" => Some(Self::Xacommit),
            "XAROLLBACK" => Some(Self::Xarollback),
            "MHEARTBEAT" => Some(Self::Mheartbeat),
            _ => None,
        }
    }
}
/// *数据库类型*
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Type {
    Typecompatibleproto2 = 0,
    Oracle = 1,
    Mysql = 2,
    Pgsql = 3,
}
impl Type {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Typecompatibleproto2 => "TYPECOMPATIBLEPROTO2",
            Self::Oracle => "ORACLE",
            Self::Mysql => "MYSQL",
            Self::Pgsql => "PGSQL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TYPECOMPATIBLEPROTO2" => Some(Self::Typecompatibleproto2),
            "ORACLE" => Some(Self::Oracle),
            "MYSQL" => Some(Self::Mysql),
            "PGSQL" => Some(Self::Pgsql),
            _ => None,
        }
    }
}
