#![allow(clippy::empty_docs, clippy::doc_lazy_continuation)]

// Generated by prost-build from Canal upstream .proto files.
// The build script compiles the proto files and outputs the generated
// Rust code into src/, using prost-build's out_dir("src/").
//
// The upstream Java package is: com.alibaba.otter.canal.protocol
//
// NOTE: EntryProtocol.proto had EntryType.HEARTBEAT renamed to
// EntryType.INNERHEARTBEAT to resolve a C++ scoping conflict with
// PacketType.HEARTBEAT from CanalProtocol.proto.
// The wire-format numeric value (4) is preserved, so protocol
// compatibility is maintained.
include!("com.alibaba.otter.canal.protocol.rs");
