[package]
name = "canal-connector"
version.workspace = true
edition.workspace = true
[dependencies]
tokio.workspace = true
futures.workspace = true
async-trait.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
rdkafka.workspace = true
canal-common = { path = "../canal-common" }
canal-sink = { path = "../canal-sink" }
