[package]
name = "canal-sink"
version.workspace = true
edition.workspace = true
[dependencies]
tokio.workspace = true
async-trait.workspace = true
tracing.workspace = true
canal-common = { path = "../canal-common" }
canal-store = { path = "../canal-store" }
canal-filter = { path = "../canal-filter" }
canal-prometheus = { path = "../canal-prometheus" }
[dev-dependencies]
tokio.workspace = true
