[package]
name = "canal-server"
version.workspace = true
edition.workspace = true
[dependencies]
tokio.workspace = true
tokio-util.workspace = true
async-trait.workspace = true
tracing.workspace = true
thiserror.workspace = true
bytes.workspace = true
chrono.workspace = true
futures.workspace = true
prost.workspace = true
dashmap.workspace = true
canal-common = { path = "../canal-common" }
canal-proto = { path = "../canal-proto" }
canal-binlog = { path = "../canal-binlog" }
canal-store = { path = "../canal-store" }
[dev-dependencies]
tokio.workspace = true
futures.workspace = true
