[package]
name = "canal-instance"
version.workspace = true
edition.workspace = true
[dependencies]
tokio.workspace = true
tracing.workspace = true
canal-common = { path = "../canal-common" }
canal-binlog = { path = "../canal-binlog" }
canal-store = { path = "../canal-store" }
canal-filter = { path = "../canal-filter" }
canal-sink = { path = "../canal-sink" }
canal-connector = { path = "../canal-connector" }
dashmap.workspace = true
async-trait.workspace = true
